<?xml version="1.0" encoding="utf-8"?><Database Name="Dealership" Class="VehiclesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TYLER-PC\TYLER;Initial Catalog=Dealership;Integrated Security=True" SettingsObjectName="Group_Project_Diagram.My.MySettings" SettingsPropertyName="DealershipConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vehicles" Member="Vehicles">
    <Type Name="Vehicle" Id="ID1">
      <Column Name="vehicleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="make" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="model" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vehicleYear" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bodyStyle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vinNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="condition" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerInfo" Member="CustomerInfos">
    <Type Name="CustomerInfo">
      <Column Name="customerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zipcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="wPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="paymentType" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="licenseNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="licenseExp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="carWashSpecial" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="tradeInCredit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.spDeleteVehicle" Method="spDeleteVehicle">
    <Parameter Name="vehicleID" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spSearchVehicleYear" Method="spSearchVehicleYear">
    <Parameter Name="vehicleYear" Type="System.String" DbType="NVarChar(50)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.spSearchVehicleMake" Method="spSearchVehicleMake">
    <Parameter Name="make" Type="System.String" DbType="NVarChar(50)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.spSearchVehicleModel" Method="spSearchVehicleModel">
    <Parameter Name="model" Type="System.String" DbType="NVarChar(50)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.spInsertVehicle" Method="spInsertVehicle">
    <Parameter Name="make" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="model" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="vehicleYear" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="bodyStyle" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="color" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="vinNumber" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="condition" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spGetCustomerInfo" Method="spGetCustomerInfo">
    <ElementType Name="spGetCustomerInfoResult">
      <Column Name="customerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(101) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>