<?xml version="1.0" encoding="utf-8"?><Database Name="Dealership" Class="VehiclesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TYLER-PC\TYLER;Initial Catalog=Dealership;Integrated Security=True" SettingsObjectName="Group_Project_Diagram.My.MySettings" SettingsPropertyName="DealershipConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Vehicles" Member="Vehicles">
    <Type Name="Vehicle" Id="ID1">
      <Column Name="vehicleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="make" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="model" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vehicleYear" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="bodyStyle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="color" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vinNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="condition" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="price" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerInfo" Member="CustomerInfos">
    <Type Name="CustomerInfo">
      <Column Name="customerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zipcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="wPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="paymentType" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="licenseNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="licenseExp" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="carWashSpecial" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="tradeInCredit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeInfo" Member="EmployeeInfos">
    <Type Name="EmployeeInfo">
      <Column Name="employeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="zipcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cPhone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="vehiclesSold" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="isManager" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CheckingAccount" Member="CheckingAccounts">
    <Type Name="CheckingAccount">
      <Column Name="accountName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="accountNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="routingNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="checkNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CreditCard" Member="CreditCards">
    <Type Name="CreditCard">
      <Column Name="ccNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="expDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cvn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cardName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Accounting" Member="Accountings">
    <Type Name="Accounting">
      <Column Name="employeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="incentive" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="dailySales" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="spotyBonus" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="transID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="month" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="day" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.spDeleteVehicle" Method="spDeleteVehicle">
    <Parameter Name="vehicleID" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spSearchVehicleYear" Method="spSearchVehicleYear">
    <Parameter Name="vehicleYear" Type="System.String" DbType="NVarChar(50)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.spSearchVehicleMake" Method="spSearchVehicleMake">
    <Parameter Name="make" Type="System.String" DbType="NVarChar(50)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.spSearchVehicleModel" Method="spSearchVehicleModel">
    <Parameter Name="model" Type="System.String" DbType="NVarChar(50)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.spInsertVehicle" Method="spInsertVehicle">
    <Parameter Name="make" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="model" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="vehicleYear" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="bodyStyle" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="color" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="vinNumber" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="condition" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="price" Type="System.Double" DbType="Float" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spGetEmployeeInfo" Method="spGetEmployeeInfo">
    <ElementType Name="spGetEmployeeInfoResult2">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Residential Information]" Member="Residential_Information" Type="System.String" DbType="NVarChar(204)" CanBeNull="true" />
      <Column Name="[Home Phone]" Member="Home_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Cell Phone]" Member="Cell_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Vehicles Sold]" Member="Vehicles_Sold" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spRemoveCustomer" Method="spRemoveCustomer">
    <Parameter Name="customerID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spRemoveEmployee" Method="spRemoveEmployee">
    <Parameter Name="employeeID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertEmployee" Method="spInsertEmployee">
    <Parameter Name="fName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="lName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="street" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="city" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="state" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="zipcode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="hPhone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="cPhone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="vehiclesSold" Type="System.Int32" DbType="Int" />
    <Parameter Name="isManager" Type="System.String" DbType="Char(10)" />
    <ElementType Name="spInsertEmployeeResult1">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Residential Information]" Member="Residential_Information" Type="System.String" DbType="NVarChar(204)" CanBeNull="true" />
      <Column Name="[Home Phone]" Member="Home_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Cell Phone]" Member="Cell_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spGetCustomerInfo" Method="spGetCustomerInfo">
    <ElementType Name="spGetCustomerInfoResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Residential Information]" Member="Residential_Information" Type="System.String" DbType="NVarChar(204)" CanBeNull="true" />
      <Column Name="[Home Phone]" Member="Home_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Cell Phone]" Member="Cell_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Payment Type]" Member="Payment_Type" Type="System.String" DbType="Char(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spInsertCheckingAccountInfo" Method="spInsertCheckingAccountInfo">
    <Parameter Name="accountName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="accountNumber" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="routingNumber" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="checkNumber" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertCreditCardInfo" Method="spInsertCreditCardInfo">
    <Parameter Name="ccNumber" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="expDate" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="cvn" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="cardName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="type" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spInsertCustomer" Method="spInsertCustomer">
    <Parameter Name="fName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="lName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="street" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="city" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="state" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="zipcode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="hPhone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="cPhone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="paymentType" Type="System.String" DbType="Char(10)" />
    <Parameter Name="licenseNumber" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="licenseExp" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="carWashSpecial" Type="System.String" DbType="Char(4)" />
    <Parameter Name="tradeInCredit" Type="System.Int32" DbType="Int" />
    <ElementType Name="spInsertCustomerResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Residential Information]" Member="Residential_Information" Type="System.String" DbType="NVarChar(204)" CanBeNull="true" />
      <Column Name="[Home Phone]" Member="Home_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Cell Phone]" Member="Cell_Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSelectPersonalSales" Method="spSelectPersonalSales">
    <ElementType Name="spSelectPersonalSalesResult">
      <Column Name="[Employee ID]" Member="Employee_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="[Total Individual Sales]" Member="Total_Individual_Sales" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSearchSalesForPerson" Method="spSearchSalesForPerson">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="spSearchSalesForPersonResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="[Day of Sale]" Member="Day_of_Sale" Type="System.String" DbType="NVarChar(152) NOT NULL" CanBeNull="false" />
      <Column Name="[Daily Sales]" Member="Daily_Sales" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSelectMonthlySales" Method="spSelectMonthlySales">
    <ElementType Name="spSelectMonthlySalesResult">
      <Column Name="Month" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Monthly Sales]" Member="Monthly_Sales" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spSelectDailySales" Method="spSelectDailySales">
    <ElementType Name="spSelectDailySalesResult">
      <Column Name="Month" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Day" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Daily Sales]" Member="Daily_Sales" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.spDeleteSales" Method="spDeleteSales">
    <Parameter Name="transID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.spGetAllSalesInfo" Method="spGetAllSalesInfo">
    <ElementType Name="spGetAllSalesInfoResult">
      <Column Name="[Transaction ID]" Member="Transaction_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Date of Sale]" Member="Date_of_Sale" Type="System.String" DbType="NVarChar(152) NOT NULL" CanBeNull="false" />
      <Column Name="[Employee Name]" Member="Employee_Name" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="[Daily Sales]" Member="Daily_Sales" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>